// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormSleeveController from "./form_sleeve_controller.js"
application.register("form-sleeve", FormSleeveController)

import SwitchboardController from "./switchboard_controller.js"
application.register("switchboard", SwitchboardController)
