// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormController from "./form_controller.js"
application.register("form", FormController)

import FormSleeveController from "./form_sleeve_controller.js"
application.register("form-sleeve", FormSleeveController)

import ListController from "./list_controller.js"
application.register("list", ListController)

import ListItemActionsController from "./list_item_actions_controller.js"
application.register("list-item-actions", ListItemActionsController)

import ListItemController from "./list_item_controller.js"
application.register("list-item", ListItemController)

import SwitchboardController from "./switchboard_controller.js"
application.register("switchboard", SwitchboardController)

import UiModalController from "./ui_modal_controller.js"
application.register("ui-modal", UiModalController)
