// This file is auto-generated by ./bin/rails view_component:stimulus_manifest:update
// Run that command whenever you add a new controller in ViewComponent

import { application } from "../javascript/controllers/application"

import Navigation__MobileSidebarComponentController from "./navigation/mobile_sidebar_component_controller.js"
application.register("navigation--mobile-sidebar-component", Navigation__MobileSidebarComponentController)

import Navigation__SidebarComponentController from "./navigation/sidebar_component_controller.js"
application.register("navigation--sidebar-component", Navigation__SidebarComponentController)

import Resource__UserAccountComponentController from "./resource/user_account_component_controller.js"
application.register("resource--user-account-component", Resource__UserAccountComponentController)

import Resource__UserProfileComponentController from "./resource/user_profile_component_controller.js"
application.register("resource--user-profile-component", Resource__UserProfileComponentController)
