class DashboardsController < SpeicherController

  skip_before_action :authenticate_user!, only: :landing
  skip_before_action :set_resource, only: :landing 
  before_action :find_landing, only: :landing

  #
  # when someone accesses the application with no endpoint
  # they should go here
  #
  def landing
    if @dashboard
      render inline: @dashboard.body, layout: @dashboard.layout, locals: {dashboard: @dashboard }
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def dashboard_params
      params.require(:dashboard).permit(:name, :layout, :body)
    end


    # Find the proper landing for this request - when possible
    def find_landing
      unless user_signed_in?
        @dashboard = Dashboard.find(params[:lid]) rescue nil
        @dashboard ||= new_dashboard
      else
        if current_account != current_user.account
          @dashboard = current_account.dashboard rescue new_dashboard
        else
          @dashboard = (current_user.profile.dashboard rescue false) || (current_user.account.dashboard rescue false) || new_dashboard
        end
      end
    end

    def new_dashboard
      Dashboard.new(
        layout: "application", 
        name: "dashboard not found!", 
        body: %(
          <div style='margin: 2rem'>
            <h1>Requested Dashboard Was Not Found!</h1>
            <p>Fix this <a style='color: #345678' href='/dashboards'>here</a> if you like</p>
            <p>This is the "<%= dashboard.name %>" dashboard generated by the system in the event that no dashboard was found</p>
          </div>
        )
      )
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:dashboard).permit(:name, :layout, :body, :theme_primary_color, :theme_secondary_color, :theme_accented_color, :theme_styles)
    end

    def find_resources_queried options
      # get <selectize> lookups
      if request.format.symbol==:json
        Dashboard.search Dashboard.all, params[:q]
      else
        Dashboard.search Dashboard.all, params[:q]
      end
    end

end
